"""
Django settings for CheckObjection project.

Generated by 'django-admin startproject' using Django 5.1.3.
"""

import os
from pathlib import Path
from dotenv import load_dotenv  # 新增：导入dotenv

# 加载.env文件
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# 从环境变量获取敏感配置
SECRET_KEY = os.environ.get('SECRET_KEY','zt1DzMSi-oi4Xer9Xc2vhnpGkZK2XJ4vYY2jTIxUBpnlGuIOEY8ErHjz2FOHdM9gbW4')

# DEBUG模式：环境变量值为'true'则开启，否则关闭
DEBUG = os.environ.get('DEBUG', 'false').lower() == 'true'

# 允许的主机：从环境变量读取，逗号分隔转列表
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition
INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "CheckObjectionApp.apps.CheckobjectionappConfig",
    'rest_framework',
    'channels'
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "CheckObjection.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "CheckObjection.wsgi.application"


# Database
# 保持my.cnf配置（也可改为环境变量，这里保留原方式）
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get('MYSQL_DATABASE'),  # 对应.env中的MYSQL_DATABASE
        "USER": os.environ.get('MYSQL_USER'),      # 对应.env中的MYSQL_USER
        "PASSWORD": os.environ.get('MYSQL_PASSWORD'),  # 对应.env中的MYSQL_PASSWORD
        "HOST": os.environ.get('MYSQL_HOST', 'localhost'),  # 建议补充MYSQL_HOST到.env（默认localhost）
        "PORT": os.environ.get('MYSQL_PORT', '3306'),      # 建议补充MYSQL_PORT到.env（默认3306）
        "OPTIONS": {
            'charset': 'utf8',
        }
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = False
USE_TZ = False


# Celery配置（从环境变量获取）
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL')

# 加在 CELERY_BROKER_URL 配置后面
print("当前CELERY_BROKER_URL：", CELERY_BROKER_URL)

# CELERY_BROKER_URL = 'amqp://admin:123456@192.168.231.100:5672//'
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_WORKER_POOL = 'solo'
CELERY_WORKER_CONCURRENCY = 1


# Judge0配置（从环境变量获取）
JUDGE0_BASE_URL = os.environ.get('JUDGE0_BASE_URL')
JUDGE0_TIMEOUT = int(os.environ.get('JUDGE0_TIMEOUT', 30))  # 默认30秒


# Static files
STATIC_URL = "static/"
STATIC_ROOT = '/app/static'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Redis缓存配置（从环境变量获取）
REDIS_HOST = os.environ.get('REDIS_HOST')
REDIS_PORT = os.environ.get('REDIS_PORT')
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD')

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "PASSWORD": REDIS_PASSWORD,
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# simpleui配置
SIMPLEUI_LOGIN_PARTICLES = True


# ASGI和Channels配置
ASGI_APPLICATION = "CheckObjection.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, int(REDIS_PORT))],
            "password": REDIS_PASSWORD,
        },
    },
}

AUTH_USER_MODEL = 'auth.User'

# 缓存相关常量
CACHE_KEY_HIT = 'cache_hit'
DB_QUERY_KEY = 'db_query'

