"""
Django settings for CheckObjection project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-g*(t+k1!reudu!@*lj9-*-)3owc=rd#g5+uin9#&*+!2@68imv"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = []
# 加入 '127.0.0.1' 和 'localhost'，支持两种本地访问方式
ALLOWED_HOSTS = ['127.0.0.1', 'localhost','6cdaf627.r8.cpolar.cn']

# Application definition

INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "CheckObjectionApp.apps.CheckobjectionappConfig",
    'rest_framework',
    'channels'
]

REST_FRAMEWORK = {
    # 如果没有以下设置，或者确保包含了可浏览API的渲染器
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # 确保有这一行
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "CheckObjection.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "CheckObjection.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        # "NAME": "jia_go",
        # "USER": "root",
        # "PASSWORD": "MONKEY20041218",
        # "HOST": "127.0.0.1",
        # "PORT": "3306",
        "OPTIONS":{
            'read_default_file': 'my.cnf',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = False

USE_TZ = False

# Celery配置
CELERY_BROKER_URL = 'amqp://admin:123456@192.168.231.100:5672//'  # RabbitMQ地址
CELERY_RESULT_BACKEND = 'redis://:MONKEY20041218@192.168.231.100:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
# 在 Celery 配置部分添加以下内容
CELERY_WORKER_POOL = 'solo'  # Windows 推荐单进程模式，避免 prefork 问题
CELERY_WORKER_CONCURRENCY = 1  # solo 模式下并发数设为 1（单进程）

# Judge0配置
JUDGE0_BASE_URL = "http://192.168.231.100:2358"
JUDGE0_TIMEOUT = 30

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://192.168.231.100:6379/0",  # 默认使用0号数据库
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,  # 连接超时时间（秒）
            "SOCKET_TIMEOUT": 5,          # 读写操作超时时间（秒）
            # 如果Redis服务器设置了密码，请添加以下配置
            # "PASSWORD": "your-redis-password-here",
            'PASSWORD': 'MONKEY20041218'
        }

    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# simpleui的配置
SIMPLEUI_LOGIN_PARTICLES = True

# SIMPLEUI_LOGIN_URL = "login"
# SIMPLEUI_LOGOUT_URL = "logout"
# SIMPLEUI_LOGIN_REDIRECT_URL = "/"

# settings.py

# ASGI_APPLICATION="django_channels_demo.routing.application"
ASGI_APPLICATION="CheckObjection.asgi.application"
# ASGI_APPLICATION = 'CheckObjection.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("192.168.231.100", 6379)],  # Redis地址
            "password": "MONKEY20041218",  # 对应Redis密码
        },
    },
}
