"""
Django settings for CheckObjection project.

Generated by 'django-admin startproject' using Django 5.1.3.
"""
"""
oj-platform-based-on-django/
├── .dockerignore
├── .gitignore
├── Dockerfile
├── Jenkinsfile
├── README.md
├── db.sqlite3
├── docker-compose.yml
├── manage.py
├── requirements.txt
├── run_dev.py
├── CheckObjection/                  # 项目主配置目录
│   ├── __init__.py
│   ├── asgi.py
│   ├── routing.py
│   ├── settings.py                  # Django 全局配置
│   ├── urls.py                      # 主URL配置
│   └── wsgi.py
├── CheckObjectionApp/               # 核心应用目录
│   ├── __init__.py
│   ├── admin.py                     # 后台管理配置
│   ├── apps.py                      # 应用配置
│   ├── code.py                      # 验证码生成逻辑
│   ├── constants.py                 # 常量定义
│   ├── consumers.py                 # Channels 消费者（WebSocket处理）
│   ├── fonts/                       # 字体文件目录（用于验证码）
│   │   └── Monaco.ttf               # 验证码使用的字体
│   ├── forms.py                     # 表单定义
│   ├── migrations/                  # 数据库迁移文件
│   │   └── __init__.py
│   ├── models.py                    # 数据模型（如Contest等）
│   ├── serializers.py               # DRF序列化器
│   ├── templates/                   # 模板文件目录
│   │   ├── CheckObjection/
│   │   │   ├── try.html             # 演示页面
│   │   │   ├── CheckObjection_detail.html  # 题目详情页
│   │   │   ├── CheckObjection_design.html  # 题目设计页
│   │   │   ├── CheckOjection_test.html     # 题目测试页
│   │   │   ├── contest/
│   │   │   │   └── contest_detail.html     # 比赛详情页
│   │   │   └── submission/
│   │   │       ├── contest_submission.html  # 比赛提交页
│   │   │       ├── base_submission.html     # 提交基础模板
│   │   │       └── practice_submission.html # 练习提交页
│   │   ├── submission/
│   │   │   └── submission_detail.html       # 提交详情页
│   │   ├── infomation/
│   │   │   └── intr.html                    # 介绍页面
│   │   └── CheckObjection_Index.html        # 平台首页
│   ├── templatetags/                # 自定义模板标签
│   ├── tests.py                     # 测试文件
│   ├── urls.py                      # 应用URL配置
│   ├── urls/                        # URL子模块目录
│   ├── utils/                       # 工具函数目录
│   ├── views.py                     # 视图函数（主视图）
│   └── views/                       # 视图子模块目录
│       ├── judge.py                 # 判题相关视图（如比赛提交判题）
│       ├── contests.py              # 比赛相关视图（如排行榜重定向）
│       ├── topics.py                # 题目相关视图（如题目详情与提交）
│       ├── submissions.py           # 提交记录相关视图（如我的提交）
│       └── base.py                  # 基础视图（如首页）
├── mycelery/                        # Celery相关配置（未详细展示）
├── static/                          # 静态文件源目录
│   ├── bootstrap5/                  # Bootstrap5 静态资源
│   └── libs/                        # 其他依赖库
├── staticfiles/                     # 收集后的静态文件目录（生产用）
│   ├── bootstrap5/
│   ├── libs/
│   └── rest_framework/
│       └── docs/
│           ├── css/
│           │   └── base.css
│           └── js/
│               └── api.js           # DRF文档JS
└── .idea/                           # PyCharm项目配置
    ├── modules.xml
    ├── vcs.xml
    ├── misc.xml
    ├── jsLibraryMappings.xml
    ├── inspectionProfiles/
    │   ├── Project_Default.xml
    │   └── profiles_settings.xml
    ├── dataSources.xml              # 数据库连接配置
    └── .gitignore                   # IDE忽略文件配置
"""

import os
from pathlib import Path
from dotenv import load_dotenv  # 新增：导入dotenv

# 加载.env文件
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# 从环境变量获取敏感配置
SECRET_KEY = os.environ.get('SECRET_KEY','zt1DzMSi-oi4Xer9Xc2vhnpGkZK2XJ4vYY2jTIxUBpnlGuIOEY8ErHjz2FOHdM9gbW4')

# DEBUG模式：环境变量值为'true'则开启，否则关闭
# DEBUG = os.environ.get('DEBUG', 'false').lower() == 'true'
DEBUG = True

# 允许的主机：从环境变量读取，逗号分隔转列表
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition
INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "CheckObjectionApp.apps.CheckobjectionappConfig",
    'rest_framework',
    'channels'
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "CheckObjection.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "CheckObjection.wsgi.application"


# Database
# 保持my.cnf配置（也可改为环境变量，这里保留原方式）
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get('MYSQL_DATABASE'),  # 对应.env中的MYSQL_DATABASE
        "USER": os.environ.get('MYSQL_USER'),      # 对应.env中的MYSQL_USER
        "PASSWORD": os.environ.get('MYSQL_PASSWORD'),  # 对应.env中的MYSQL_PASSWORD
        "HOST": os.environ.get('MYSQL_HOST'),  # 建议补充MYSQL_HOST到.env（默认localhost）
        "PORT": os.environ.get('MYSQL_PORT'),      # 建议补充MYSQL_PORT到.env（默认3306）
        "OPTIONS": {
            'charset': 'utf8',
        }
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# 只在生产环境启用严格的安全设置
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
#
# # HSTS设置（强制浏览器使用HTTPS）
# SECURE_HSTS_SECONDS = 31536000    # 1年
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# 其他安全设置
# SECURE_REFERRER_POLICY = 'same-origin'  # 控制Referer头信息
# Internationalization
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = False
USE_TZ = False


# Judge0配置（从环境变量获取）
JUDGE0_BASE_URL = os.environ.get('JUDGE0_BASE_URL')
JUDGE0_TIMEOUT = int(os.environ.get('JUDGE0_TIMEOUT', 30))  # 默认30秒


# Static files
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Redis缓存配置（从环境变量获取）
REDIS_HOST = os.environ.get('REDIS_HOST')
REDIS_PORT = os.environ.get('REDIS_PORT')
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD')

if REDIS_PASSWORD:
    REDIS_URL = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0'
else:
    REDIS_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "PASSWORD": REDIS_PASSWORD,
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# simpleui配置
SIMPLEUI_LOGIN_PARTICLES = True


# ASGI和Channels配置
ASGI_APPLICATION = "CheckObjection.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, int(REDIS_PORT))],
            "password": REDIS_PASSWORD,
        },
    },
}

AUTH_USER_MODEL = 'auth.User'

# 缓存相关常量
CACHE_KEY_HIT = 'cache_hit'
DB_QUERY_KEY = 'db_query'

LOGIN_URL = 'CheckObjectionApp:login'