# Generated by Django 5.1.3 on 2025-09-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="题目")),
                ("content", models.TextField(verbose_name="描述")),
                ("example", models.TextField(verbose_name="示例")),
                (
                    "pub_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
            ],
            options={
                "verbose_name": "题目信息",
                "verbose_name_plural": "题目信息",
                "ordering": ["-pub_time"],
            },
        ),
    ]
