# Generated by Django 5.1.3 on 2025-09-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CheckObjectionApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="回答内容")),
                ("notes", models.TextField(verbose_name="备注")),
                (
                    "pub_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
            ],
            options={
                "verbose_name": "回答备注",
                "verbose_name_plural": "回答备注",
                "ordering": ["-pub_time"],
            },
        ),
    ]
