# Generated by Django 5.1.3 on 2025-09-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CheckObjectionApp", "0002_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="topic_id",
            field=models.BigIntegerField(default=1, verbose_name="问题题号"),
            preserve_default=False,
        ),
    ]
