# Generated by Django 5.1.3 on 2025-09-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CheckObjectionApp", "0003_answer_topic_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="user_name",
            field=models.TextField(default=0, verbose_name="姓名"),
            preserve_default=False,
        ),
    ]
