# Generated by Django 5.1.3 on 2025-09-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CheckObjectionApp", "0004_answer_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="level",
            field=models.IntegerField(default=0),
        ),
    ]
