# Generated by Django 5.1.3 on 2025-09-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CheckObjectionApp", "0005_topic_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("use_id", models.BigIntegerField(verbose_name="id号")),
                ("finish", models.BigIntegerField(default=0, verbose_name="完成数量")),
            ],
        ),
    ]
