# Generated by Django 5.1.3 on 2025-09-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CheckObjectionApp", "0006_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="use_id",
            new_name="user_id",
        ),
    ]
