# Generated by Django 5.1.3 on 2025-10-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CheckObjectionApp", "0007_rename_use_id_userprofile_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ["-pub_time"],
                "verbose_name": "用户回答模型",
                "verbose_name_plural": "用户回答模型",
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["-pub_time"],
                "verbose_name": "题目信息模型",
                "verbose_name_plural": "题目信息模型",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "用户附加信息模型",
                "verbose_name_plural": "用户附加信息模型",
            },
        ),
    ]
