# Generated by Django 5.1.3 on 2025-10-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckObjectionApp', '0008_alter_answer_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='titleSlug',
            field=models.CharField(blank=True, max_length=200, verbose_name='题目Slug'),
        ),
    ]
