# Generated by Django 5.1.3 on 2025-10-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckObjectionApp', '0009_topic_titleslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='titleSlug',
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, verbose_name='输入数据')),
                ('expected_output', models.TextField(verbose_name='期望输出')),
                ('is_sample', models.BooleanField(default=False, verbose_name='是否样例')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('score', models.IntegerField(default=10, verbose_name='分数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('titleSlug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_slug', to='CheckObjectionApp.topic', verbose_name='题目别名')),
            ],
            options={
                'db_table': 'judge_test_cases',
                'ordering': ['order', 'id'],
            },
        ),
    ]
