# Generated by Django 5.1.3 on 2025-10-14 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckObjectionApp', '0010_remove_topic_titleslug_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='titleSlug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_set', to='CheckObjectionApp.topic', verbose_name='题目别名'),
        ),
    ]
