# Generated by Django 5.1.3 on 2025-10-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckObjectionApp', '0012_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
