# Generated by Django 5.1.3 on 2025-10-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckObjectionApp', '0014_submission_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='topic_id',
            new_name='old_topic_id',
        ),
    ]
