# Generated by Django 5.1.3 on 2025-10-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckObjectionApp', '0015_rename_topic_id_submission_old_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='CheckObjectionApp.topic'),
        ),
    ]
