# Generated by Django 5.1.3 on 2025-10-19 11:31

from django.db import migrations


def migrate_topic_relation(apps, schema_editor):
    # 获取模型（必须用apps.get_model，不能直接导入）
    Submission = apps.get_model('CheckObjectionApp', 'Submission')
    Topic = apps.get_model('CheckObjectionApp', 'topic')  # 模型名通常为首字母大写

    # 遍历所有提交，将old_topic_id转换为外键
    for submission in Submission.objects.all():
        if not submission.old_topic_id:
            continue  # 跳过空值

        try:
            # 转换：old_topic_id是字符串，需转为整数（Topic的id是默认自增整数）
            topic_id = int(submission.old_topic_id)
            # 关联对应的Topic
            topic = Topic.objects.get(id=topic_id)
            submission.topic = topic
            submission.save()
        except (ValueError, Topic.DoesNotExist):
            # 处理异常：如果转换失败或Topic不存在，设置为null
            submission.topic = None
            submission.save()


class Migration(migrations.Migration):
    dependencies = [
        ('CheckObjectionApp', '0016_submission_topic'),  # 依赖上一步添加topic字段的迁移
    ]

    operations = [
        migrations.RunPython(migrate_topic_relation),  # 执行数据迁移函数
    ]