# Generated by Django 5.1.3 on 2025-10-19 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckObjectionApp', '0017_auto_20251019_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='CheckObjectionApp.topic'),
        ),
    ]
