# Generated by Django 5.1.3 on 2025-10-19 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckObjectionApp', '0018_alter_submission_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='比赛标题')),
                ('description', models.TextField(verbose_name='比赛描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='访问密码')),
                ('penalty_time', models.IntegerField(default=20, verbose_name='错误提交罚时(分钟)')),
                ('allow_register', models.BooleanField(default=True, verbose_name='允许报名')),
                ('ranking_frozen', models.BooleanField(default=False, verbose_name='封榜')),
                ('frozen_time', models.DateTimeField(blank=True, null=True, verbose_name='封榜时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_disqualified', models.BooleanField(default=False, verbose_name='是否取消资格')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='CheckObjectionApp.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='参与者')),
            ],
            options={
                'verbose_name': '比赛参与者',
                'verbose_name_plural': '比赛参与者',
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckObjectionApp.contest')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckObjectionApp.contestparticipant')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckObjectionApp.submission')),
            ],
            options={
                'verbose_name': '比赛提交记录',
                'verbose_name_plural': '比赛提交记录',
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='题目顺序')),
                ('score', models.IntegerField(default=100, verbose_name='题目分数')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_topics', to='CheckObjectionApp.contest')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckObjectionApp.topic', verbose_name='题目')),
            ],
            options={
                'verbose_name': '比赛题目',
                'verbose_name_plural': '比赛题目',
                'ordering': ['order'],
                'unique_together': {('contest', 'topic')},
            },
        ),
    ]
