# Generated by Django 5.1.3 on 2025-10-23 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckObjectionApp', '0019_contest_contestparticipant_contestsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsubmission',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submissions', to='CheckObjectionApp.submission'),
        ),
    ]
